### ISSUE TITLE
Errors unloading the plugin

### ISSUE THREAD

**Issue by gk7huki** [breathingstatue/blender-plugin#2]
Some non-existent properties are referenced in `unregister()`, so the plugin doesn't unload cleanly.
```bash
Exception in module unregister(): '[...]/blender-plugin/__init__.py'
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 453, in disable
    mod.unregister()
  File "[...]/blender-plugin/__init__.py", line 982, in unregister
    del bpy.types.Scene.apply_rotation_on_export
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Scene' has no attribute 'apply_rotation_on_export'
```

**Comment by breathingstatue** [comment]
fixed and checked

**Comment by gk7huki** [comment]
Hey, it seems this commit https://github.com/breathingstatue/blender-plugin/commit/efb9926967cd8e734d32cf920f6dc7bcdf629bff undid the recent fixes :/

**Comment by breathingstatue** [comment]
I included them later in the next commit. I accidentally mixed up the updates in the first push.

**Comment by gk7huki** [comment]
> I included them later in the next commit. I accidentally mixed up the updates in the first push.

Hmm no, the latest code doesn't have any of the fixes. https://github.com/breathingstatue/blender-plugin/commit/efb9926967cd8e734d32cf920f6dc7bcdf629bff undid the fixes. The next commit https://github.com/breathingstatue/blender-plugin/commit/b6e76ba1ffa2390186541cc2e43a91ba1b889cf7 is an empty commit.

See picture below:

![Screenshot_20240320_215012](https://github.com/breathingstatue/blender-plugin/assets/7953957/0c7f31b6-3259-4c78-b25d-77909049ceaa)

**Comment by breathingstatue** [comment]
Sorry about the Confusion. I accidentially uploaded the old code. No it's been fixed.
